# Generated by Django 4.2.1 on 2023-05-07 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qbwc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlAccount",
            fields=[
                (
                    "baseobjectmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="qbwc.baseobjectmixin",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("full_name", models.CharField(max_length=60)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("account_type", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("help_name", models.CharField(blank=True, max_length=30, null=True)),
                ("help_description", models.TextField(blank=True, null=True)),
                ("display", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("qbwc.baseobjectmixin",),
        ),
        migrations.CreateModel(
            name="OtherNameList",
            fields=[
                (
                    "baseobjectmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="qbwc.baseobjectmixin",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
            ],
            options={
                "abstract": False,
            },
            bases=("qbwc.baseobjectmixin",),
        ),
    ]
