# Generated by Django 4.2.1 on 2023-05-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glaccount",
            name="mark_for_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="glaccount",
            name="account_number",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="glaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("AccountsPayable", "AccountsPayable"),
                    ("AccountsReceivable", "AccountsReceivable"),
                    ("Bank", "Bank"),
                    ("CostOfGoodsSold", "CostOfGoodsSold"),
                    ("CreditCard", "CreditCard"),
                    ("Equity", "Equity"),
                    ("Expense", "Expense"),
                    ("FixedAsset", "FixedAsset"),
                    ("Income", "Income"),
                    ("LongTermLiability", "LongTermLiability"),
                    ("NonPosting", "NonPosting"),
                    ("OtherAsset", "OtherAsset"),
                    ("OtherCurrentAsset", "OtherCurrentAsset"),
                    ("OtherCurrentLiability", "OtherCurrentLiability"),
                    ("OtherExpense", "OtherExpense"),
                    ("OtherIncome", "OtherIncome"),
                ],
                max_length=50,
            ),
        ),
    ]
