# Generated by Django 4.2.1 on 2023-06-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_glaccount_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glaccount",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
