# Generated by Django 4.2.1 on 2023-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_glaccount_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glaccount",
            name="account_number",
            field=models.CharField(max_length=6),
        ),
    ]
