# Generated by Django 4.2.1 on 2023-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_vendor_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="display",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="help_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="help_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
