# Generated by Django 4.2.1 on 2023-06-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("qblists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "qbwc_list_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("qbwc_time_created", models.DateTimeField(blank=True, null=True)),
                ("qbwc_time_modified", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=60)),
                ("full_name", models.CharField(max_length=60)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "qbwc_list_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("qbwc_time_created", models.DateTimeField(blank=True, null=True)),
                ("qbwc_time_modified", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("reference_number", models.CharField(max_length=12)),
                ("memo", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("amount", models.FloatField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.glaccount",
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creditcards.creditcard",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qblists.othernamelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
