# Generated by Django 4.2.1 on 2023-06-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creditcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardcharge",
            name="qbwc_txn_number",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
