# Generated by Django 4.2.1 on 2023-06-04 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("creditcards", "0002_rename_content_type_creditcardcharge_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creditcardcharge",
            old_name="vendor",
            new_name="content_type",
        ),
    ]
