# Generated by Django 4.2.1 on 2023-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qblists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="othernamelist",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
