# Generated by Django 4.2.1 on 2023-05-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qbwc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseobjectmixin",
            name="batch_status",
        ),
        migrations.AddField(
            model_name="task",
            name="batch_id",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="batch_status",
            field=models.CharField(
                choices=[("BATCHED", "BATCHED"), ("UN_BATCHED", "UN_BATCHED")],
                default="UN_BATCHED",
                max_length=20,
            ),
        ),
    ]
